language: python

cache:
  - pip: True

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

install:
  # Updates
  - sudo apt-get update
  - pip install codecov coveralls
  - pip install -r requirements.txt
  # Install snspin
  - python setup.py install

# command to run tests
script:
  # Get the test data
  - wget https://lapp-owncloud.in2p3.fr/index.php/s/AMZmqyQe6kvSMJ4/download
  - tar zxf download
  - rm -rf download
  # Run the tests
  - coverage run --source="snspin" setup.py test

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http

after_success:
  - codecov
  - coveralls

